### PR TITLE
add spawned check

### PR DESCRIPTION
**Pull request by lyhistory**
check whether tickets been spawned already

### CODE REVIEW

**Comment by hboon** [comment]
Maybe good to add a comment that it’s an O(n) operation. It slows down as there are more tokens spawned?

**Comment by lyhistory** [comment]
@James-Sangalli which IDE should use for correct indent, it align nicely in notepad++, but dunno why after commit it changed

**Comment by lyhistory** [comment]
done, and I enabled payable for spawnPassTo according to @zhangzhongnan928 new requirement

**Comment by hboon** [comment]
Re indentation, it's likely because you are mixing spaces and tabs. In general just use whatever is used in the file you are editing. This particular file seems to be using spaces originally.

**Comment by lyhistory** [comment]
@hboon it's done, thanks

**Pull request merged**
