### PR TITLE
don't approve me, work in progress for cryptokitties xml

### PR DESCRIPTION
**Pull request by James-Sangalli**
for #34 
@James-Sangalli sorted stuff into sub-directories in this pR>

### CODE REVIEW

**Comment by hboon** [comment]
1. Is it supposed to be complete? For example, there's "coralsunrise" for eye-colour that isn't in the XML.

2. For https://www.cryptokitties.co/kitty/800058, I tried mapping with `getKitty(800058)` (and getting `genes`) to get `678778009017880207790542205580649507656770004622593132176275284610754689` which converted to binary is `011000100101100101000110100100011010011101110001100100100001010010111101011010110010101110010000111100000000000000001010011010001100010000100100001010010100010000111000000000100111011110111101110010110010000001001000000101111010100010000001`

And with the XML, I'm getting:

pattern 00111 = 7 = totescbasic_8 (should be amur)
body 10100 = 20 = ?
eye color 00001 = 1 gold (should be coralsunrise)

Am I doing it wrong?

3. We need to call `getKitty(kittyId)` (`genes` is the last element in the result) and this isn't part of ERC721. Maybe we need a way to define the `getKitty()` call and how to interpret the results in the asset definition too..

**Comment by hboon** [comment]
Also, do we support specifying the bitmask as both binary and hex strings? i.e. the parser has to read the length to determine if it is binary/hex? Or should we just use hex? (kitty's is in binary and ticket's is in hex now)

**Comment by James-Sangalli** [comment]
@hboon hmmm, seems the image I am basing off from the article does not match the reality?

**Comment by James-Sangalli** [comment]
@colourful-land bump

**Comment by hboon** [comment]
@James-Sangalli I might be parsing the numbers incorrectly. Would be good if you can help verify. But it does seem to be missing some of the cattribute values.

**Comment by hboon** [comment]
@James-Sangalli it seems the XML's bitmask assumes a reversed order of the gene groups:

For example, body which is this in the XML:

00000000000000011111 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

should be:

0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000001111 body

Similarly:

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111000000000000000000000000000000000000000000000000000000000000 eye-type/shape
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001111100000000000000000000 pattern-type

But unless there's another source, we'll have to figure out the missing cattribute values ourselves.

**Comment by colourful-land** [comment]
@James-Sangalli 1. Approve this first so I can approve yours; 2) suggest to split this into 2 pr in the future since "sort into folders" is a big change.

**Comment by colourful-land** [comment]
@James-Sangalli says this one should wait - don't approve it because he is still working on it

**Comment by James-Sangalli** [comment]
Replaced by services like OpenSea

**Pull request closed without merging**
