### PR TITLE
Clean up casting and make bitwise operations consistent

### PR DESCRIPTION
**Pull request by hboon**

### CODE REVIEW

**Comment by lyhistory** [comment]
hi, @hboon  I don't think it works when you remove the casting bytes32(), 
please check the sample I just tested https://ethfiddle.com/VsuZJTjez4
the reason is that, by my observe, if you don't use bytes32 to cast it first, it will only give you the last lower one byte, and then when you shift it left in loop, the lower byte will always be 0, and byte(***) always only gives you the last one byte which is 0, result in my example:
0x3a32303138313133303030303030302b30383030000100005649500000412d**31**
you only get
0x3100000000000000000000000000000000000000000000000000000000000000
but one thing you're correct that we can remove the _tempTicket by
message[i * 32 + j] = byte(bytes32(tickets[i] << (8*j)));
image

**Comment by James-Sangalli** [comment]
Hi @lyhistory, @hboon and I tested this and discovered that it makes no difference due to the byte() casting

**Comment by lyhistory** [comment]
hi @hboon 
based on your changes I made some more changes based on #15 , 
and I made a pull request you can review it #97 @James-Sangalli 
you can improve based on my version, I tested it, this version is working for spawnable token

**Comment by lyhistory** [comment]
@hboon sorry, ignore my previous changes on contract

**Pull request merged**
