### PR TITLE
add TokenScriptTest.sol

### PR DESCRIPTION
**Pull request by James-Sangalli**

### CODE REVIEW

**Comment by colourful-land** [comment]
what does it do?

**Comment by James-Sangalli** [comment]
@colourful-land it's for the EntryToken example in tokenscript, it has a hardcoded balance.

**Comment by James-Sangalli** [comment]
Partly solves: https://gist.github.com/hboon/7be08b075e3f1b43fe979bc7c0681d64

**Comment by hboon** [comment]
Should the `isExpired()` function mentioned in the TokenScript be included?

**Comment by James-Sangalli** [comment]
> Should the `isExpired()` function mentioned in the TokenScript be included?

Don't think we need that, I can remove it from the TokenScript as we refine the tutorial with the new updates to the schema etc.

**Comment by James-Sangalli** [comment]
@colourful-land bump

**Pull request merged**
